### ISSUE TITLE
Calls to get_epsg() hang forever if the API isn't working

### ISSUE THREAD

**Issue by Brideau** [cmollet/epsg_ident#4]
Hi there, I found that the `.get_epsg()` method would hang without responding, blocking execution permanently if the call to the backup API, `http://prj2epsg.org/search.json` was not responding. 

Can you perhaps have this fail gracefully, or provide the option to let the user specify that it not fall back to the API at all?

Thank you! Really appreciate your work on this.

**Comment by cmollet** [comment]
Thanks for letting me know @Brideau! Both of your suggestions make sense; I'll try to take a crack at them later this week.

**Comment by cmollet** [comment]
Hey @Brideau , sorry it took me longer than I said, but see the updated README for how to skip calling the prj2epsg.org API with a command-line option. Feel free to reopen or open a new issue if it doesn't suit your needs. Cheers!

**Comment by Brideau** [comment]
No worries! And it looks like you can also pass `call_remote_api=False` when you init as well if you're using it in an application, correct?

**Comment by cmollet** [comment]
Yes, good catch! `get_epsg()` should just return `None` if `sridentify` is instantiated with `call_remote_api=False` and it can't find a match. I almost exclusively use it in CLI mode so I sort of neglected Python API mode but I'll update the README with that info.

**Comment by Brideau** [comment]
Perfect, thank you!
